### PR TITLE
Faq comp

### PR DESCRIPTION
**Pull request by hanien**

### CODE REVIEW

**Comment by this-oliver** [comment]
hey buddy @hanien you're trying to merge into master lol

**Comment by this-oliver** [comment]
Also, could you make the FAQ's into cards. This would make things easier to read... but would require breaking down each faq into a sub-component

**Comment by Naief** [comment]
Fixed a merge conflict in index.js.

**Comment by Naief** [comment]
I think you forgot to add 'faq' to the Navigation Bar @hanien

**Pull request closed without merging**
